# Generated by Django 4.1.1 on 2022-09-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Offered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_offering_name', models.TextField(max_length=255)),
                ('other_course_offering_details', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_course_schedule_details', models.TextField(max_length=255)),
                ('course_offering_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.course_offered')),
            ],
        ),
        migrations.CreateModel(
            name='Research_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_research_id', models.IntegerField()),
                ('project_name', models.TextField(max_length=255)),
                ('project_description', models.TextField(max_length=255)),
                ('other_details', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('first_name', models.TextField(max_length=255)),
                ('last_name', models.TextField(max_length=255)),
                ('job_title', models.TextField(max_length=255)),
                ('phone_number', models.TextField(max_length=15)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('other_staff_details', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('other_student_details', models.TextField(verbose_name=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Course_Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sch_id', to='sms.course_scheduled')),
                ('student_course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.students')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Research_Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_research_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.research_projects')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_on_Research_Projects',
            fields=[
                ('date_from', models.DateField(primary_key=True, serialize=False)),
                ('date_to', models.DateField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.research_projects')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Courses_Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_offering_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.course_offered')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.staff')),
            ],
        ),
    ]
